Metrics/LineLength:
  Max: 100

Metrics/AbcSize:
  Max: 25

Metrics/MethodLength:
  Max: 30

Style/Documentation:
  Enabled: false

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented

AllCops:
  TargetRubyVersion: 2.2
